version: '3.7'
services: 
    app:
        container_name: devcontainercompose
        build: .
        user: node
        working_dir: /home/node/app
        expose: 
            - 3000
        environment: 
            PORT: 3000
        volumes: 
            - ../app:/home/node/app
        ports: 
            - 3000:3000
        tty: true